### ISSUE TITLE
Tensorflow Op is not supported: AddV2

### ISSUE THREAD

**Issue by Sregnier1** [cloud-annotations/object-detection-live-stream#1]
I am trying to use the model I made in Cloud Annotations. I have Node js Version  12.16.1 and npm version 6.13.4. I am on a windows x86_64 system. Tensorflow is not locally on my machine.
I am able to run your example just fine but when I rename your 'model_web' file and copy my 'model_web' file into the public directory I get this error: object-detection@0.0.8:1 Uncaught (in promise) Error:
 Tensorflow Op is not supported: AddV2
    at aS.mapNode (object-detection@0.0.8:1)
    at object-detection@0.0.8:1
    at Array.reduce (<anonymous>)
    at aS.transformGraph (object-detection@0.0.8:1)
    at NS.<anonymous> (object-detection@0.0.8:1)
    at object-detection@0.0.8:1
    at Object.next (object-detection@0.0.8:1)
    at n (object-detection@0.0.8:1)

any help would be great. I can provide more information as well.

**Comment by bourdakos1** [comment]
Hi there, I recently updated the model training to TensorFlow 1.15 which requires a newer version of tfjs (1.4.0 I think). I just forgot to update this repo, I will fix it as soon as possible.

Thanks you!

**Comment by bourdakos1** [comment]
Should work now

**Comment by Sregnier1** [comment]
Works great, thank you so much for the quick response and fix!
